# data
training_file: data/SCOTUS/train.txt
val_file: data/SCOTUS/valid.txt
test_file: data/SCOTUS/test.txt
data_name: SCOTUS
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: true
remove_no_label_data: false
add_special_tokens: false

# train
seed: 1337
epochs: 50
batch_size: 16
optimizer: adam
learning_rate: 0.003
weight_decay: 0
patience: 10
shuffle: false

# eval
eval_batch_size: 16
monitor_metrics: ['Macro-F1', 'Micro-F1', 'P@1', 'P@3', 'P@5', 'nDCG@5']
early_stopping_metric: Micro-F1
val_metric: Micro-F1

# model
model_name: CNNLWAN_exps
init_weight: kaiming_uniform
loss_function: binary_cross_entropy_with_logits
network_config:
  attn_mode: vanilla
  output_mode: vanilla
  embed_dropout: 0
  encoder_dropout: 0
  filter_sizes: [2]
  num_filter_per_size: 50
  freeze_embed: true


# pretrained vocab / embeddings
embed_file: glove.840B.300d
normalize_embed: false
vocab_file: null