# data
training_file: data/ECtHRB/train.txt
val_file: data/ECtHRB/valid.txt
test_file: data/ECtHRB/test.txt
data_name: ECtHRB
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: true
# Follow https://github.com/jamesmullenbach/caml-mimic/blob/master/datasets.py#L45
# to remove training and validation instances that have no labels.
remove_no_label_data: true

# train
seed: 1337
epochs: 50
batch_size: 16
optimizer: adam
learning_rate: 0.003
weight_decay: 0
patience: 10
shuffle: false

# eval
eval_batch_size: 16
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@3', 'P@5']
val_metric: 'Micro-F1'

# model
model_name: KimCNN
init_weight: xavier_uniform
network_config:
  activation: null
  embed_dropout: 0.2
  post_encoder_dropout: 0.2
  filter_sizes: [4]
  num_filter_per_size: 500
  
# pretrained vocab / embeddings
embed_file: glove.840B.300d
normalize_embed: false
vocab_file: null
