# data
training_file: data/ECtHRB/train.txt
val_file: data/ECtHRB/valid.txt
test_file: data/ECtHRB/test.txt
data_name: ECtHRB
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: true
remove_no_label_data: false
add_special_tokens: false

# train
seed: 1337
epochs: 50
batch_size: 16
optimizer: adam
learning_rate: 0.0003
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 16
monitor_metrics: ['Macro-F1', 'Micro-F1', 'P@1', 'P@3', 'P@5', 'nDCG@5']
early_stopping_metric: Micro-F1
val_metric: Micro-F1

# model
model_name: CNNLWAN_exps
init_weight: kaiming_uniform
loss_function: binary_cross_entropy_with_logits
network_config:
  attn_mode: vanilla
  output_mode: relu
  embed_dropout: 0.6
  encoder_dropout: 0.2
  filter_sizes: [6]
  num_filter_per_size: 250
  linear_size: [128]
  freeze_embed: false


# pretrained vocab / embeddings
embed_file: glove.840B.300d
normalize_embed: false
vocab_file: null
