# data
training_file: data/EUR-Lex/train.txt
test_file: data/EUR-Lex/test.txt
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: false

# train
seed: 1240 # 1337
epochs: 50
batch_size: 16
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 10
shuffle: true
lr_scheduler: ReduceLROnPlateau
scheduler_config:
  factor: 0.9
  patience: 9
  min_lr: 0.0001


# eval
eval_batch_size: 32
monitor_metrics: ['Another-Macro-F1', 'Macro-F1', 'Micro-F1', 'P@1', 'P@5', 'RP@5', 'nDCG@5']
val_metric: nDCG@5
val_size: 200

# model
model_name: AttentionRNN
init_weight: xavier_uniform
loss_function: binary_cross_entropy_with_logits
network_config:
  embed_dropout: 0.2
  encoder_dropout: 0.5
  rnn_dim: 512
  rnn_layers: 1
  linear_size: [256]
  freeze_embed_training: True

# pretrained vocab / embeddings
embed_file: glove.840B.300d # glove.6B.200d
