# data
training_file: data/EUR-Lex/train.txt
test_file: data/EUR-Lex/test.txt
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: false

# train
seed: 1337
epochs: 50
batch_size: 16
optimizer: adam
learning_rate: 0.001
weight_decay: 0
patience: 10
shuffle: true


# eval
eval_batch_size: 16
monitor_metrics: ['Another-Macro-F1', 'Macro-F1', 'Micro-F1', 'P@1', 'P@5', 'RP@5', 'nDCG@5']
val_metric: P@5

# model
model_name: BiLSTMLWAN_exps
loss_function: binary_cross_entropy_with_logits
init_weight: kaiming_uniform
network_config:
  attn_mode: tanh
  output_mode: vanilla
  embed_dropout: 0.6
  encoder_dropout: 0.2
  rnn_dim: 1024
  rnn_layers: 1
  freeze_embed: false

# pretrained vocab / embeddings
embed_file: glove.840B.300d